#!/usr/bin/env bash


if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
cd /var/www/html/app/ && composer install

php /var/www/html/app/artisan migrate
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf